// <auto-generated />
using System;
using Hamburger_Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hamburger_Application.Migrations
{
    [DbContext(typeof(HamburgerDbContext))]
    [Migration("20230717171237_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "56dd3b13-2f3e-4f7a-89b2-1a84043a3def",
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(1372),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "fddf04de-8442-4a9b-af53-132235f9acc5",
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(1386),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConfirmCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Dessert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Desserts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(6461),
                            IsActive = false,
                            Name = "Brownie",
                            Photo = "cafddece-875e-4d0c-830c-72b3e194666c_Brownie.jpg",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(6469),
                            IsActive = false,
                            Name = "Milkshake",
                            Photo = "fb998a43-9809-4ebc-a546-ce63ca896be8_MilkShake.jpg",
                            Price = 40m
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(6471),
                            IsActive = false,
                            Name = "Cheesecake",
                            Photo = "ee446133-2bb0-46af-b257-3d1a8930432f_CheeseCake.jpg",
                            Price = 60m
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(6472),
                            IsActive = false,
                            Name = "Ice Cream",
                            Photo = "1d5c1238-10f9-49e6-a388-a541d1d64e4c_IcaCream.jpg",
                            Price = 30m
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(6473),
                            IsActive = false,
                            Name = "Puding",
                            Photo = "a01529c3-70cf-4b43-af5c-db1f8f9a921d_Puding.jpg",
                            Price = 40m
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasFilter("[MenuId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8483),
                            IsActive = false,
                            Name = "Coke-S",
                            Photo = "6240f4b6-c927-4898-9c76-6968b54c1e39_Coke.jpg",
                            Price = 40m,
                            Size = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8489),
                            IsActive = false,
                            Name = "Ayran-S",
                            Photo = "a7e28042-2e4a-443e-860d-0f0cbd0d640c_Ayran.jpg",
                            Price = 25m,
                            Size = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8490),
                            IsActive = false,
                            Name = "Coke Zero-S",
                            Photo = "1117576e-e2a3-42a5-8dc0-9f5d90fd0e80_CokeZero.jpg",
                            Price = 45m,
                            Size = 0
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8491),
                            IsActive = false,
                            Name = "Cold Tea-S",
                            Photo = "914e854b-f076-455c-aeab-49f8d8f4ca8e_ColdTea.jpg",
                            Price = 35m,
                            Size = 0
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8492),
                            IsActive = false,
                            Name = "Mineral Water-S",
                            Photo = "d2ffceeb-e929-43e1-9fc6-df7838fa6aa2_MineralWater.jpg",
                            Price = 15m,
                            Size = 0
                        },
                        new
                        {
                            Id = 6,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8493),
                            IsActive = false,
                            Name = "Coke-M",
                            Photo = "6240f4b6-c927-4898-9c76-6968b54c1e39_Coke.jpg",
                            Price = 45m,
                            Size = 2
                        },
                        new
                        {
                            Id = 7,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8495),
                            IsActive = false,
                            Name = "Ayran-M",
                            Photo = "a7e28042-2e4a-443e-860d-0f0cbd0d640c_Ayran.jpg",
                            Price = 30m,
                            Size = 2
                        },
                        new
                        {
                            Id = 8,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8496),
                            IsActive = false,
                            Name = "Coke Zero-M",
                            Photo = "1117576e-e2a3-42a5-8dc0-9f5d90fd0e80_CokeZero.jpg",
                            Price = 50m,
                            Size = 2
                        },
                        new
                        {
                            Id = 9,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8497),
                            IsActive = false,
                            Name = "Cold Tea-M",
                            Photo = "914e854b-f076-455c-aeab-49f8d8f4ca8e_ColdTea.jpg",
                            Price = 40m,
                            Size = 2
                        },
                        new
                        {
                            Id = 10,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8498),
                            IsActive = false,
                            Name = "Mineral Water-M",
                            Photo = "d2ffceeb-e929-43e1-9fc6-df7838fa6aa2_MineralWater.jpg",
                            Price = 20m,
                            Size = 2
                        },
                        new
                        {
                            Id = 11,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8499),
                            IsActive = false,
                            Name = "Coke-L",
                            Photo = "6240f4b6-c927-4898-9c76-6968b54c1e39_Coke.jpg",
                            Price = 50m,
                            Size = 3
                        },
                        new
                        {
                            Id = 12,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8500),
                            IsActive = false,
                            Name = "Ayran-L",
                            Photo = "a7e28042-2e4a-443e-860d-0f0cbd0d640c_Ayran.jpg",
                            Price = 35m,
                            Size = 3
                        },
                        new
                        {
                            Id = 13,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8501),
                            IsActive = false,
                            Name = "Coke Zero-L",
                            Photo = "1117576e-e2a3-42a5-8dc0-9f5d90fd0e80_CokeZero.jpg",
                            Price = 55m,
                            Size = 3
                        },
                        new
                        {
                            Id = 14,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8502),
                            IsActive = false,
                            Name = "Cold Tea-L",
                            Photo = "914e854b-f076-455c-aeab-49f8d8f4ca8e_ColdTea.jpg",
                            Price = 45m,
                            Size = 3
                        },
                        new
                        {
                            Id = 15,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 785, DateTimeKind.Local).AddTicks(8504),
                            IsActive = false,
                            Name = "Mineral Water-L",
                            Photo = "d2ffceeb-e929-43e1-9fc6-df7838fa6aa2_MineralWater.jpg",
                            Price = 25m,
                            Size = 3
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Fries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasFilter("[MenuId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Frieses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(351),
                            IsActive = false,
                            Name = "Potatoes - S",
                            Photo = "301422bb-3c9f-4670-87ec-52f6bb49510e_Potatoes.jpg",
                            Price = 20m,
                            Size = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(356),
                            IsActive = false,
                            Name = "Onion Ring - S",
                            Photo = "40149d5b-324f-40d3-802c-0866bc9edac8_OnionRings.jpg",
                            Price = 22m,
                            Size = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(358),
                            IsActive = false,
                            Name = "Nugget - S",
                            Photo = "f012288d-4cb5-4546-a5a1-82a2e34457ce_Nuggets.jpg",
                            Price = 25m,
                            Size = 0
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(359),
                            IsActive = false,
                            Name = "Chicken Tenders - S",
                            Photo = "1e165d0c-cdad-4956-a803-a291756320b1_ChickenTenders.jpg",
                            Price = 25m,
                            Size = 0
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(360),
                            IsActive = false,
                            Name = "Potatoes - M",
                            Photo = "301422bb-3c9f-4670-87ec-52f6bb49510e_Potatoes.jpg",
                            Price = 24m,
                            Size = 2
                        },
                        new
                        {
                            Id = 6,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(364),
                            IsActive = false,
                            Name = "Onion Ring - M",
                            Photo = "40149d5b-324f-40d3-802c-0866bc9edac8_OnionRings.jpg",
                            Price = 26m,
                            Size = 2
                        },
                        new
                        {
                            Id = 7,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(365),
                            IsActive = false,
                            Name = "Nugget - M",
                            Photo = "f012288d-4cb5-4546-a5a1-82a2e34457ce_Nuggets.jpg",
                            Price = 29m,
                            Size = 2
                        },
                        new
                        {
                            Id = 8,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(366),
                            IsActive = false,
                            Name = "Chicken Tenders - M",
                            Photo = "1e165d0c-cdad-4956-a803-a291756320b1_ChickenTenders.jpg",
                            Price = 29m,
                            Size = 2
                        },
                        new
                        {
                            Id = 9,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(368),
                            IsActive = false,
                            Name = "Potatoes - L",
                            Photo = "301422bb-3c9f-4670-87ec-52f6bb49510e_Potatoes.jpg",
                            Price = 28m,
                            Size = 3
                        },
                        new
                        {
                            Id = 10,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(369),
                            IsActive = false,
                            Name = "Onion Ring - L",
                            Photo = "40149d5b-324f-40d3-802c-0866bc9edac8_OnionRings.jpg",
                            Price = 30m,
                            Size = 3
                        },
                        new
                        {
                            Id = 11,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(370),
                            IsActive = false,
                            Name = "Nugget - L",
                            Photo = "f012288d-4cb5-4546-a5a1-82a2e34457ce_Nuggets.jpg",
                            Price = 33m,
                            Size = 3
                        },
                        new
                        {
                            Id = 12,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(371),
                            IsActive = false,
                            Name = "Chicken Tenders - L",
                            Photo = "1e165d0c-cdad-4956-a803-a291756320b1_ChickenTenders.jpg",
                            Price = 33m,
                            Size = 3
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Hamburger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasFilter("[MenuId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Hamburger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(2341),
                            IsActive = false,
                            Name = "Whopper",
                            Photo = "27c952d4-c958-4bce-87ad-6cb40a743067_Whopper.jpg",
                            Price = 120m
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(2347),
                            IsActive = false,
                            Name = "Texas SmokeHouse",
                            Photo = "43773966-353c-4741-9a0e-9d3642aea7e3_TexasSmokeHouse.jpg",
                            Price = 140m
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(2348),
                            IsActive = false,
                            Name = "Fish Royale",
                            Photo = "074e56a6-ab87-48b1-b948-8ddc5ff84c97_FishRoyale.jpg",
                            Price = 110m
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(2349),
                            IsActive = false,
                            Name = "Big King",
                            Photo = "e7bcba7f-5e1f-4b11-81fe-8f423b4bb26f_BigKing.jpg",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 786, DateTimeKind.Local).AddTicks(2351),
                            IsActive = false,
                            Name = "Chicken Royale",
                            Photo = "0c8d85ff-19e8-4550-b079-f83d1e8b863a_ChickenRoyale.jpg",
                            Price = 95m
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int?>("FriesId")
                        .HasColumnType("int");

                    b.Property<int?>("HamburgerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(1850),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 1,
                            IsActive = false,
                            Name = "Whopper Menu",
                            Photo = "085732b2-62a9-473a-9c94-198bf0b38d9c_WhopperMenu.jpg",
                            Price = 150m
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(1863),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 2,
                            IsActive = false,
                            Name = "Texas SmokeHouse Menu",
                            Photo = "03e49b85-7d1b-4a0e-8d18-47d97756a570_TexasSmokeHouseMenu.jpg",
                            Price = 170m
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(1866),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 3,
                            IsActive = false,
                            Name = "Fish Royale Menu",
                            Photo = "c7e2b9ad-b7b7-476f-9e1d-32c502cf5686_FishRoyaleMenu.jpg",
                            Price = 140m
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(1867),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 4,
                            IsActive = false,
                            Name = "Big King Menu",
                            Photo = "3ae527d5-e1ca-474d-b550-9acca3afb9b8_BigKingMenu.jpg",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(1868),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 5,
                            IsActive = false,
                            Name = "Chicken Royale Menu",
                            Photo = "70e64328-09a0-4e6c-90c5-23868ba18a03_ChickenRoyaleMenu.jpg",
                            Price = 120m
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Sauce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Sauce");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(4562),
                            IsActive = false,
                            Name = "Ranch",
                            Photo = "7b5e0551-d08d-4092-8c72-ff370ea64c57_RanchSauce.jpg",
                            Price = 15m
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(4567),
                            IsActive = false,
                            Name = "Ketchup",
                            Photo = "f8b55022-2756-43dd-823d-6b94e43d9807_KetchupSauce.jpg",
                            Price = 10m
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(4569),
                            IsActive = false,
                            Name = "Mayonnaise",
                            Photo = "7821c0f8-2b4b-4b46-b958-6fe2dec26bd7_MayonaisseSauce.jpg",
                            Price = 10m
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 20, 12, 35, 788, DateTimeKind.Local).AddTicks(4570),
                            IsActive = false,
                            Name = "Barbeque",
                            Photo = "cad13c53-f4c9-4b94-aaa7-cb20855cd41e_BarbequeSauce.jpg",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Dessert", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Desserts")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Drink", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Menu", "Menu")
                        .WithOne("Drink")
                        .HasForeignKey("Hamburger_Application.Entities.Concrete.Drink", "MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Drinks")
                        .HasForeignKey("OrderId");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Fries", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Menu", "Menu")
                        .WithOne("Fries")
                        .HasForeignKey("Hamburger_Application.Entities.Concrete.Fries", "MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Fries")
                        .HasForeignKey("OrderId");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Hamburger", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Menu", "Menu")
                        .WithOne("Hamburger")
                        .HasForeignKey("Hamburger_Application.Entities.Concrete.Hamburger", "MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Hamburgers")
                        .HasForeignKey("OrderId");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Menu", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Menus")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Order", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Sauce", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Sauces")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Menu", b =>
                {
                    b.Navigation("Drink");

                    b.Navigation("Fries");

                    b.Navigation("Hamburger");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Order", b =>
                {
                    b.Navigation("Desserts");

                    b.Navigation("Drinks");

                    b.Navigation("Fries");

                    b.Navigation("Hamburgers");

                    b.Navigation("Menus");

                    b.Navigation("Sauces");
                });
#pragma warning restore 612, 618
        }
    }
}
