// <auto-generated />
using System;
using Hamburger_Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hamburger_Application.Migrations
{
    [DbContext(typeof(HamburgerDbContext))]
    partial class HamburgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "335de442-1cdd-428d-b9b3-78e7ee47666d",
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(1545),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "f2755e47-daa9-4abc-b9d6-e1dcd875ca0c",
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(1558),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Dessert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Desserts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(4739),
                            IsActive = false,
                            Name = "Brownie",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(4747),
                            IsActive = false,
                            Name = "Milkshake",
                            Price = 40m
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(4748),
                            IsActive = false,
                            Name = "Cheesecake",
                            Price = 60m
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(4749),
                            IsActive = false,
                            Name = "Ice Cream",
                            Price = 30m
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(4750),
                            IsActive = false,
                            Name = "Puding",
                            Price = 40m
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasFilter("[MenuId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(5948),
                            IsActive = false,
                            Name = "Coke",
                            Price = 40m,
                            Size = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(5952),
                            IsActive = false,
                            Name = "Ayran",
                            Price = 25m,
                            Size = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(5953),
                            IsActive = false,
                            Name = "Coke Zero",
                            Price = 45m,
                            Size = 0
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(5954),
                            IsActive = false,
                            Name = "Cold Tea",
                            Price = 35m,
                            Size = 0
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(5955),
                            IsActive = false,
                            Name = "Mineral Water",
                            Price = 15m,
                            Size = 0
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Fries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasFilter("[MenuId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Frieses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(7068),
                            IsActive = false,
                            Name = "Potato",
                            Price = 20m,
                            Size = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(7071),
                            IsActive = false,
                            Name = "Onion Ring",
                            Price = 22m,
                            Size = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(7073),
                            IsActive = false,
                            Name = "Nugget",
                            Price = 25m,
                            Size = 0
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(7074),
                            IsActive = false,
                            Name = "Chicken Tenders",
                            Price = 25m,
                            Size = 0
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Hamburger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasFilter("[MenuId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Hamburger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(8537),
                            IsActive = false,
                            Name = "Whopper",
                            Price = 120m
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(8540),
                            IsActive = false,
                            Name = "Texas SmokeHouse",
                            Price = 140m
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(8541),
                            IsActive = false,
                            Name = "Fish Royale",
                            Price = 110m
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(8542),
                            IsActive = false,
                            Name = "Big King",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 458, DateTimeKind.Local).AddTicks(8543),
                            IsActive = false,
                            Name = "Chicken Royale",
                            Price = 95m
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int?>("FriesId")
                        .HasColumnType("int");

                    b.Property<int?>("HamburgerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(1922),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 1,
                            IsActive = false,
                            Name = "Whopper Menu",
                            Price = 150m
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(1933),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 2,
                            IsActive = false,
                            Name = "Texas SmokeHouse Menu",
                            Price = 170m
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(1935),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 3,
                            IsActive = false,
                            Name = "Fish Royale Menu",
                            Price = 140m
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(1936),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 4,
                            IsActive = false,
                            Name = "Big King Menu",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(1938),
                            DrinkId = 1,
                            FriesId = 1,
                            HamburgerId = 5,
                            IsActive = false,
                            Name = "Chicken Royale Menu",
                            Price = 120m
                        });
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Sauce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Sauce");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(3603),
                            IsActive = false,
                            Name = "Ranch",
                            Price = 15m
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(3607),
                            IsActive = false,
                            Name = "Ketchup",
                            Price = 10m
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(3608),
                            IsActive = false,
                            Name = "Mayonnaise",
                            Price = 10m
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2023, 7, 17, 11, 8, 52, 460, DateTimeKind.Local).AddTicks(3609),
                            IsActive = false,
                            Name = "Barbeque",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Dessert", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Desserts")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Drink", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Menu", "Menu")
                        .WithOne("Drink")
                        .HasForeignKey("Hamburger_Application.Entities.Concrete.Drink", "MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Drinks")
                        .HasForeignKey("OrderId");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Fries", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Menu", "Menu")
                        .WithOne("Fries")
                        .HasForeignKey("Hamburger_Application.Entities.Concrete.Fries", "MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Fries")
                        .HasForeignKey("OrderId");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Hamburger", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Menu", "Menu")
                        .WithOne("Hamburger")
                        .HasForeignKey("Hamburger_Application.Entities.Concrete.Hamburger", "MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Hamburgers")
                        .HasForeignKey("OrderId");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Menu", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Menus")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Order", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Sauce", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.Order", "Order")
                        .WithMany("Sauces")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Hamburger_Application.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Menu", b =>
                {
                    b.Navigation("Drink");

                    b.Navigation("Fries");

                    b.Navigation("Hamburger");
                });

            modelBuilder.Entity("Hamburger_Application.Entities.Concrete.Order", b =>
                {
                    b.Navigation("Desserts");

                    b.Navigation("Drinks");

                    b.Navigation("Fries");

                    b.Navigation("Hamburgers");

                    b.Navigation("Menus");

                    b.Navigation("Sauces");
                });
#pragma warning restore 612, 618
        }
    }
}
